spring.application.name=SummeryB
server.port=${PORT:8082}
server.address=0.0.0.0

#32 caracters MIN
#if user tries to cahange the ROLE -> will no longer match
application.security.jwt.secret-key =${JWT_SECRET:}

#Admin stuff
app.admin.email=${ADMIN_EMAIL:realadmin@test.com}
app.admin.password=${ADMIN_PASSWORD:}




#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


#DB -> Postgres soon trust
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://5432/summeryDB
#how does docker even do this..
spring.datasource.username=${DB_USER:summery_user}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


spring.datasource.continue-on-error=true
springdoc.swagger-ui.path=/swagger-ui.html

#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#oh we learning security
